title: lums.io
# baseurl: "/vida"

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-84692207-1
disqus_shortname:
